// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Reflection;
using System.Text;
using System.Xml;
using System.Xml.Linq;

using Microsoft.Azure.ApiManagement.PolicyToolkit.Serialization;

namespace Microsoft.Azure.ApiManagement.PolicyToolkit.IO;

public static class FileUtils
{
    public class Data
    {
        public required XElement Element;
        public required XmlWriterSettings XmlWriterSettings;
        public required bool FormatCode;
        public required string SourceFilePath;
        public required string SourceFolder;
        public required string OutputFilePath;
        public required string OutputFolder;

        /// <summary>
        /// When <c>true</c> (default) the document is emitted in the Razor-like
        /// <c>rawxml</c> format with policy expressions written verbatim. When
        /// <c>false</c> the document is emitted in the fully XML-encoded <c>xml</c>
        /// format where reserved characters inside expressions are escaped.
        /// </summary>
        public bool RawXml = true;
    }

    public static string WriteToFile(Data data)
    {
        // In xml format policy expressions are XML-encoded during serialization, so the
        // C# must be reflowed on the document tree (raw text) before it is written;
        // reformatting the encoded string would reparse entities like &lt; as C#.
        if (data.FormatCode && !data.RawXml)
        {
            RazorCodeFormatter.FormatExpressions(data.Element);
        }

        var codeBuilder = new StringBuilder();
        using (var writer = CustomXmlWriter.Create(codeBuilder, data.XmlWriterSettings, rawExpressions: data.RawXml))
        {
            writer.Write(new XComment(" This file is generated by the Azure API Management Policy Toolkit "));
            writer.Write(new XComment($" Version: {Assembly.GetExecutingAssembly().GetName().Version} "));
            writer.Write(data.Element);
        }

        var xml = codeBuilder.ToString();
        // In rawxml format expressions are written verbatim, so the C# can be reflowed
        // on the serialized string.
        if (data.FormatCode && data.RawXml)
        {
            xml = RazorCodeFormatter.Format(xml);
        }

        var fileRelativePath = Path.GetDirectoryName(Path.GetRelativePath(data.SourceFolder, data.SourceFilePath))!;
        var targetFolder = Path.Combine(data.OutputFolder, fileRelativePath);
        var targetFile = Path.Combine(targetFolder, data.OutputFilePath);
        var directoryPath = Path.GetDirectoryName(targetFile);
        if (directoryPath is not null && !Directory.Exists(directoryPath))
        {
            Directory.CreateDirectory(directoryPath);
        }

        File.WriteAllText(targetFile, xml);

        return targetFile;
    }
}