blank_issues_enabled: true
contact_links:
  - name: Ask a question on Stack Overflow 💬
    url: https://stackoverflow.com/questions/tagged/azure-api-management
    about: Ask a question or request support for using Azure API Management policy toolkit.
  - name: Open a discussion 🗣
    url: https://github.com/Mielek/apim-policy-toolkit/discussions
    about: Start a discussion about the project or its policies.
