name: Test example project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Create new packages
        run: dotnet pack
      - name: Restore dependencies
        working-directory: ./example
        run: dotnet restore
      - name: Restore tool
        working-directory: ./example
        run: dotnet tool restore
      - name: Build with dotnet
        working-directory: ./example
        run: dotnet build --no-restore
      - name: Test with dotnet
        working-directory: ./example
        run: dotnet test --no-build --logger trx --results-directory "TestResults"
      - name: Upload dotnet test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: ./example/TestResults
      - name: Compile policies
        working-directory: ./example
        run: dotnet azure-apim-policy-compiler --s .\source\ --o .\target\ --format true